model:
  nit: 500
  reg: 0.02
  ranking: emd # emd / cls / max / mean

train:
  loss: margin_ranking # cross_entropy / margin_ranking
  optimizer: adamw
  learning_rate: 0.000001
  epsilon: 0.000001
  weight_decay: 0.01

  epochs: 1
  grad_update_step: 16
